### ISSUE TITLE
Check failed: it's either a bug or inconsistent data! elasticsearch knn

### ISSUE THREAD

**Issue by pawanm09** [opendistro-for-elasticsearch/k-NN#136]
I am using the latest Amazon Machine Image. 

I indexed 100,000 vectors then I got this Error.

I am using a t2.small instance type with 2 GB Ram  & 15 GB disk.

Is it because of low RAM? 

Logs 
`
at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:662) ~[l
ucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
[2020-06-16T09:31:12,681][INFO ][o.e.c.r.a.AllocationService] [node-1] Cluster health status changed from [YELLOW]
to [RED] (reason: [shards failed [[knn-index][0]]]).
[2020-06-16T09:31:15,962][INFO ][c.a.o.j.s.JobSweeper     ] [node-1] Running full sweep
[2020-06-16T09:32:05,421][INFO ][stats_log] [node-1] ---------------------------------------------
---------------------------
Program=PerformanceAnalyzerPlugin
StartTime=1592299865.413
EndTime=Tue, 16 Jun 2020 09:32:05 UTC
Time=60008 msecs
Timing=total-time:60008.0/1
Counters=TotalError=0
EOE
[2020-06-16T09:32:28,623][WARN ][o.e.i.e.Engine] [node-1] [knn-index][0] failed engine [lucene commit f
ailed]
java.lang.Exception: Check failed: it's either a bug or inconsistent data!
at com.amazon.opendistroforelasticsearch.knn.index.v1736.KNNIndex.saveIndex(Native Method) ~[?:?]
at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer$1.run(KNN80DocV
aluesConsumer.java:106) ~[?:?]
at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer$1.run(KNN80DocV
aluesConsumer.java:104) ~[?:?]
`

**Comment by jmazanec15** [comment]
Hi @nmsaey42, digging into this a bit, I think it may be a memory issue. Here is a similar issue in [NMSLIB](https://github.com/nmslib/nmslib/issues/279). To try to reproduce it on our end, could you provide the following information:
1. How many shards are you using? Are there any replicas?
1. What is the dimensionality of the vectors?
1. What are the values for M and ef_construction?

**Comment by pawanm09** [comment]
@jmazanec15  Thanks for the reply

I also think this is memory related issue. When I increased the RAM. It works smoothly. 

1. Number of Shards: 3 with one replica
2. The dimensions of the Vector: 600
3. default value of M & ef_construction. (M= 16, ef_construction=512)

**Comment by jmazanec15** [comment]
Great! Please re-open if you experience this issue again.
