### ISSUE TITLE
`GLIBCXX_3.4.20' not found 

### ISSUE THREAD

**Issue by ftyuuu** [opendistro-for-elasticsearch/k-NN#175]
I install k-NN based on rpm, when i add document, i got this error. What should i do?
```
java.lang.UnsatisfiedLinkError: /usr/lib/libKNNIndexV1_7_3_6.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libKNNIndexV1_7_3_6.so)
        at java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]
        at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452) ~[?:?]
        at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508) ~[?:?]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2669) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:807) ~[?:?]
        at java.lang.System.loadLibrary(System.java:1907) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.v1736.KNNIndex$1.run(KNNIndex.java:41) ~[?:?]
```

**Comment by jmazanec15** [comment]
Hi @ftyuuu, this is an incompatibility with the library binary we shipped and your system. What OS are you running? We built the artifacts with Ubuntu 16 and g++ 5.4. For next release, we are planning to build with Centos 7 and g++ 4.8.

As a side note, to solve this issue, you could build the library artifact from source on your machine. [Here](https://github.com/opendistro-for-elasticsearch/k-NN/issues/163#issuecomment-662024428) is how you can build the RPM.

Please let us know if that works!

**Comment by ftyuuu** [comment]
Hi @jmazanec15, finally, i solve this problem by updating g++ from 4.8 to 4.9, and then re-make this project.
