### ISSUE TITLE
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-4"

### ISSUE THREAD

**Issue by pawanm09** [opendistro-for-elasticsearch/k-NN#189]
I am creating an index to store documents of dimension 600. 

But, After indexing around 650,000 documents the index starts crashing. 

I increased the RAM to 13 GB with 2 VCPUs & disk storage of 50 GB. 

Still, when I am indexing new documents the index gets crashed. 

--------------------------------------------------------------------------------------
**Error**
From status command: `systemctl status elasticsearch.service`

```
elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-07-30 08:48:44 UTC; 6min ago
     Docs: https://www.elastic.co
  Process: 6287 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=127)
 Main PID: 6287 (code=exited, status=127)
Jul 30 07:54:43 knn-es systemd-entrypoint[6287]: WARNING: All illegal access operations will be denied in a future release
Jul 30 07:54:43 knn-es systemd[1]: Started Elasticsearch.
Jul 30 08:48:22 knn-es systemd-entrypoint[6287]: java.lang.OutOfMemoryError: Java heap space
Jul 30 08:48:22 knn-es systemd-entrypoint[6287]: Dumping heap to /var/lib/elasticsearch/java_pid6287.hprof ...
Jul 30 08:48:25 knn-es systemd-entrypoint[6287]: Heap dump file created [1127387658 bytes in 3.517 secs]
Jul 30 08:48:42 knn-es systemd-entrypoint[6287]: Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-4"
Jul 30 08:48:44 knn-es systemd-entrypoint[6287]: fatal error in thread [elasticsearch[node-1][http_server_worker][T#1]], exiting
Jul 30 08:48:44 knn-es systemd-entrypoint[6287]: java.lang.OutOfMemoryError: Java heap space
Jul 30 08:48:44 knn-es systemd[1]: elasticsearch.service: Main process exited, code=exited, status=127/n/a
Jul 30 08:48:44 knn-es systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
```
--------------------------------------------------------------------------------------

After Starting Elasticsearch

--------------------------------------------------------------------------------------
**RAM Status:**
Command: `free`
```
              total        used        free      shared  buff/cache   available
Mem:       13301168      319784     1535956        1580    11445428    12653876
Swap:             0           0           0

```
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
**Disk Status:** 
Command: `df` 
```
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             6628804        0   6628804   0% /dev
tmpfs            1330120      896   1329224   1% /run
/dev/sda1       50633164 26696064  23920716  53% /
tmpfs            6650584      672   6649912   1% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            6650584        0   6650584   0% /sys/fs/cgroup
/dev/loop0         99328    99328         0 100% /snap/core/9665
/dev/loop1         98944    98944         0 100% /snap/core/9436
/dev/loop2        121472   121472         0 100% /snap/google-cloud-sdk/142
/dev/loop3         56320    56320         0 100% /snap/core18/1880
/dev/loop4        121600   121600         0 100% /snap/google-cloud-sdk/143
/dev/sda15        106858     3668    103190   4% /boot/efi
tmpfs            1330116        0   1330116   0% /run/user/1002
```
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
**Open Distro Info:** 
Version: 1.9.0
Installed Using: https://github.com/opendistro-for-elasticsearch/k-NN/issues/172#issuecomment-661574606

settings from: `curl -XGET https://localhost:9200/knn-index/_settings -u admin:admin --insecure`

```
{
  "knn-index": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "knn.algo_param": {
          "ef_search": "512",
          "ef_construction": "512",
          "m": "20"
        },
        "provided_name": "knn-index",
        "knn.space_type": "l2",
        "knn": "true",
        "creation_date": "1595350959293",
        "number_of_replicas": "1",
        "uuid": "4HS96MDsSRSFlxEdLiyivA",
        "version": {
          "created": "7080099"
        }
      }
    }
  }
}
```
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
**System Information**
```
Compute Engine
Ubuntu Version: 18.04
RAM: 13 GB
Disk: 50 GB SSD
```
--------------------------------------------------------------------------------------

Please help
Thanks

**Comment by jmazanec15** [comment]
Hi @nmsaey42 , I have not seen this before. What is the maximum JVM heap size for your ES process?  We will try to reproduce it.

**Comment by pawanm09** [comment]
Hello @jmazanec15 

On running this command:` java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'`

I got this: 

```
     intx CompilerThreadStackSize                  = 1024                                   {pd product} {default}
   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 213909504                                 {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 3405774848                                {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5825164                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122916538                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122916538                              {pd product} {ergonomic}
     intx ThreadStackSize                          = 1024                                   {pd product} {default}
     intx VMThreadStackSize                        = 1024                                   {pd product} {default}
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

**Comment by pawanm09** [comment]
I run it again and this time the error is: 

```
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-31 04:14:08 UTC; 2min 15s ago
     Docs: https://www.elastic.co
  Process: 31571 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=127)
 Main PID: 31571 (code=exited, status=127)
Jul 30 09:02:37 knn-es systemd-entrypoint[31571]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jul 30 09:02:37 knn-es systemd-entrypoint[31571]: WARNING: All illegal access operations will be denied in a future release
Jul 31 04:13:27 knn-es systemd-entrypoint[31571]: java.lang.OutOfMemoryError: Java heap space
Jul 31 04:13:27 knn-es systemd-entrypoint[31571]: Dumping heap to /var/lib/elasticsearch/java_pid31571.hprof ...
Jul 31 04:14:02 knn-es systemd-entrypoint[31571]: Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elasticsearch[node-1][scheduler][T#1]"
Jul 31 04:14:07 knn-es systemd-entrypoint[31571]: Heap dump file created [1128505108 bytes in 40.474 secs]
Jul 31 04:14:08 knn-es systemd-entrypoint[31571]: fatal error in thread [Thread-4], exiting
Jul 31 04:14:08 knn-es systemd-entrypoint[31571]: java.lang.OutOfMemoryError: Java heap space
Jul 31 04:14:08 knn-es systemd[1]: elasticsearch.service: Main process exited, code=exited, status=127/n/a
Jul 31 04:14:08 knn-es systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
```


**And the Response Error is**
`TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1069524496/1019.9mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1068932896/1019.4mb], new bytes reserved: [591600/577.7kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=591600/577.7kb, accounting=604188/590kb]') `

**Comment by jmazanec15** [comment]
For JVM heap, could you check `/etc/elasticsearch/jvm.options`

By default, it ships `-Xms1g` and `-Xmx1g` for initial and maximum heap size. 

I would recommend increasing this `4g` or `6g` and retrying the experiment. [This documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html) has some good pointers on setting heap size.

**Comment by pawanm09** [comment]
Hi @jmazanec15 

My JVM heap size is 1g.

After increasing it I am getting this Error: 
```
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-08-01 06:14:05 UTC; 1min 26s ago
     Docs: https://www.elastic.co
  Process: 4625 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=127)
 Main PID: 4625 (code=exited, status=127)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.jav
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at org.elasticsearch.threadpool.ThreadPool$ThreadedRunnable.run(ThreadPool.java:505)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
Aug 01 06:14:04 knn-es systemd-entrypoint[4625]:         at java.base/java.lang.Thread.run(Thread.java:832)
Aug 01 06:14:05 knn-es systemd[1]: elasticsearch.service: Main process exited, code=exited, status=127/n/a
Aug 01 06:14:05 knn-es systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
```

**Comment by jmazanec15** [comment]
Hi @nmsaey42 , are there any errors around this time in the `elasticsearch.log` file?

This file should be located at `/var/log/elasticsearch`.

**Comment by pawanm09** [comment]
@jmazanec15  

After increasing the heap size, restarting the machine solved the problem. 

Thanks for your help

**Comment by jmazanec15** [comment]
No problem! Glad it was resolved
