### ISSUE TITLE
Fix test testScriptStats_multipleShards

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#272]
When upgraded to ES version 7.10.0, number of script query requests seem to mismatch. Most likely issue with test case

REPRODUCE WITH: ./gradlew ':integTest' --tests "com.amazon.opendistroforelasticsearch.knn.plugin.action.RestKNNStatsHandlerIT.testScriptStats_multipleShards" -Dtests.seed=A4F5BF99A3533F39 -Dtests.security.manager=false -Dtests.locale=ar-AE -Dtests.timezone=Asia/Harbin -Druntime.java=14

com.amazon.opendistroforelasticsearch.knn.plugin.action.RestKNNStatsHandlerIT > testScriptStats_multipleShards FAILED
    java.lang.AssertionError: expected:<2> but was:<4>
        at __randomizedtesting.SeedInfo.seed([A4F5BF99A3533F39:18BA805562F7F047]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.amazon.opendistroforelasticsearch.knn.plugin.action.RestKNNStatsHandlerIT.testScriptStats_multipleShards(RestKNNStatsHandlerIT.java:282)

**Comment by jmazanec15** [comment]
I don't believe this is an issue with the test case. It seems like the constructor for VectorScoreScriptFactory is getting called twice per shard per query. Need to dig into this a little bit more to understand why this is happening. But, at the moment, this  appears to be a bug.
