### ISSUE TITLE
Possible bug  java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.KNNIndexV1_7_3_6")

### ISSUE THREAD

**Issue by mikepalei** [opendistro-for-elasticsearch/k-NN#49]
Hi guys,

I'm running your plugin on an AWS instance using this docker image: ferdous/odfes_elasticsearch_knn

After restarting an index I can no longer run a KNN query.

```
q = {
    "size": 10,
    "_source": ["id"],
    "query": {
        "knn": {
            "my_vector": {
                "vector": np.random.sample(4000,).tolist(),
                "k": 5
            }
        }
    }
}
```
This is the error I get:

```
[2020-02-10T09:15:10,473][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [2bfe18bf65f8] fatal error in thread [elasticsearch[2bfe18bf65f8][search][T#1]], exiting
java.lang.ExceptionInInitializerError: null
	at org.elasticsearch.index.knn.KNNIndexCache.computeIndex(KNNIndexCache.java:145) ~[?:?]
	at org.elasticsearch.index.knn.KNNIndexCache.lambda$getIndex$2(KNNIndexCache.java:125) ~[?:?]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:433) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.knn.KNNIndexCache.getIndex(KNNIndexCache.java:125) ~[?:?]
	at org.elasticsearch.index.knn.KNNWeight$1.run(KNNWeight.java:103) ~[?:?]
	at org.elasticsearch.index.knn.KNNWeight$1.run(KNNWeight.java:101) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:310) ~[?:?]
	at org.elasticsearch.index.knn.KNNWeight.scorer(KNNWeight.java:100) ~[?:?]
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:177) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:649) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	at org.apache.lucene.search.XIndexSearcher.search(XIndexSearcher.java:44) ~[elasticsearch-7.2.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:177) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:443) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:271) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:114) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:335) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:360) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.search.SearchService$2.doRun(SearchService.java:1052) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.2.0.jar:7.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.KNNIndexV1_7_3_6")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:1044) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:408) ~[?:?]
	at java.lang.SecurityManager.checkLink(SecurityManager.java:694) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:821) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1902) ~[?:?]
	at org.elasticsearch.index.knn.v1736.KNNIndex.<clinit>(KNNIndex.java:36) ~[?:?]
	... 28 more
```

**Comment by vamshin** [comment]
@mikepalei,

Thanks for filling the issue.

Please let us which docker image you were referring to? We have not released docker image for opendistro1.4 yet.

**Comment by mikepalei** [comment]
@vamshin 
I specified it in the question itself. This is the name of the image: `ferdous/odfes_elasticsearch_knn`

**Comment by vamshin** [comment]
Hi @mikepalei ,

Do you want to try opendistro1.4 docker image  
https://hub.docker.com/layers/amazon/opendistro-for-elasticsearch/1.4.0/images/sha256-7f79c000e5b4bb50790ecdd4e4fc906499000c283d83b92231b57c0fd9201618

**Comment by JuliusMannes** [comment]
Hi everyone, 

I have the same issue using the 1.4 docker image. Once a node that has indexed data on it restarts, it fails with the next query.

**Comment by jmazanec15** [comment]
Able to reproduce the issue on a 2 node ODFE cluster. Looking into the root cause and fix.

**Comment by jmazanec15** [comment]
The call to loadLibrary needs to be wrapped in a privileged action here: [here](https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/index/v1736/KNNIndex.java#L37). 

It does not fail on initial startup because index creation runs the static block in Privileged mode when KNNIndex.saveIndex is called [here](https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/index/codec/KNN80DocValuesConsumer.java#L96).

Submitted PR to address issue #53

**Comment by rishabh6788** [comment]
@mikepalei @JuliusMannes 

Could you please remove the previous amazon/opendistro-for-elasticsearch:1.4.0 image and pull the latest one and try again?

Please let us know if you are still facing the same error.

**Comment by JuliusMannes** [comment]
Works like a charm now. Thank you!
