### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by yinrong** [opendistro-for-elasticsearch/k-NN#94]
```
[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [n1] fatal error in thread [elasticsearch[n1][write][T#4]], exiting
java.lang.UnsatisfiedLinkError: no KNNIndexV1_7_3_6 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:806) ~[?:?]
        at java.lang.System.loadLibrary(System.java:1909) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.v1736.KNNIndex$1.run(KNNIndex.java:40) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.v1736.KNNIndex$1.run(KNNIndex.java:38) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.v1736.KNNIndex.<clinit>(KNNIndex.java:38) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer$2.run(KNN80DocValuesConsumer.java:178) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer$2.run(KNN80DocValuesConsumer.java:176) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.isNmsLibLatest(KNN80DocValuesConsumer.java:175) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addKNNBinaryField(KNN80DocValuesConsumer.java:77) ~[?:?]
        at com.amazon.opendistroforelasticsearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addBinaryField(KNN80DocValuesConsumer.java:68) ~[?:?]
        at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addBinaryField(PerFieldDocValuesFormat.java:114) ~[lucene-core-8.4.0.jar:8.4.0 bc02ab906445fcf4e297f4ef00ab4a54fdd72ca2 - jpountz - 2019-12-19 20:16:14]
```

**Comment by jmazanec15** [comment]
Hi Yin, could you describe the environment you are running it in?

**Comment by sarita05** [comment]
You need to add .so file in your java.library.path.
You can download .so file from below mentioned link based on your version and  keep it under /usr/lib directory followed by ES restart.
https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.3.0.0
https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.4.0.0
https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.6.0.0

**Comment by yinrong** [comment]
> You need to add .so file in your java.library.path.
> You can download .so file from below mentioned link based on your version and keep it under /usr/lib directory followed by ES restart.
> https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.3.0.0
> https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.4.0.0
> https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.6.0.0

it's right direction. but it's more complicated. the libraries have recursive dependencies. I stop trying since it's too difficult.

For this project, it's better provide tested OS versions, Linux kernel version.  Then we can re-install the system or build & run elasticsearch in docker.

**Comment by sarita05** [comment]
Yes, true. With docker version 1.6.0,  I did not face this error.
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

**Comment by yinrong** [comment]
> Hi Yin, could you describe the environment you are running it in?

Thanks for asking.  But I believe it's a hard way to go any further.

it's better this project give tested OS versions. or just use a docker image.

**Comment by yinrong** [comment]
I suppose tested OS version is in:

https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/
